spring:
  application:
    name: MY-Retail-Product-Catalog
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: POSTGRESQL
    show-sql: true

logging:
  level:
    org:
      springframework: INFO
      zalando: INFO
    com:
      my:
        retail:
          catalog: INFO
      zaxxer: INFO
    root: ERROR

logbook:
  filter:
    enabled: true
  write:
    level: INFO
  format:
    style: splunk
  exclude: [/, /actuator/**, /v3/api-docs/**, /swagger-ui/**, /index.html, /images/**, /swagger-ui.js, /lib/**, /css/**]
  strategy: body-only-if-status-at-least
  minimum-status: 400

server:
  port: 8080
  undertow:
    accesslog:
      #dir: # Undertow access log directory.
      enabled: false # Whether to enable the access log.
      pattern: common # Format pattern for access logs.
      prefix: access_log. # Log file name prefix.
      rotate: true # Whether to enable access log rotation.
      suffix: log # Log file name suffix.
    #buffer-size:  # Size of each buffer, in bytes.
    #direct-buffers:  # Whether to allocate buffers outside the Java heap.
    #io-threads:  # Number of I/O threads to create for the worker.
    eager-filter-init: true # Whether servlet filters should be initialized on startup.
    max-http-post-size: 0 # Maximum size, in bytes, of the HTTP post content.
    #worker-threads:  # Number of worker threads.

DOCKER_BUILD_PHASE: N