version: '2.2'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: Catalog@1234
      LOGSPOUT: ignore
    mem_limit: "512000000"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 30s
      timeout: 15s
      retries: 10
    networks:
      catalog-nw:
        aliases:
          - postgres
  catalog:
    image: catalog:latest
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: Catalog@1234
      LOGSPOUT: ignore
    mem_limit: "512000000"
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/actuator/health"]
      interval: 60s
      timeout: 30s
      retries: 15
    networks:
      catalog-nw:
        aliases:
          - catalog
volumes:
  postgres_data:
    ## Use the below setting for a persistent data storage. Please craete the necessary container/persistence/postgres in your current directory of docker-compose.yml
    #driver: local
    #driver_opts:
    #  type: none
    #  device: $PWD/container/persistence/postgres
    #  o: bind
networks:
  catalog-nw: